import Audio from "#/models/audio";
import AutoGeneratedPlaylist from "#/models/autoGeneratedPlaylist";
import cron from "node-cron";

// The six fields in the cron syntax represnt (in order) secs,mins,hours,day of the month,month,and day of the week.

// cron.schedule("*/2 * * * * *", () => {
//   console.log("Running a task every half seconds");
// });

const generatedPlaylist = async () => {
  const mostLikedAudios = await Audio.aggregate([
    {
      $sort: { likes: -1 },
    },
    {
      $sample: { size: 20 },
    },
    {
      $group: {
        _id: "$category",
        audios: { $push: "$$ROOT._id" }, // $$ROOT is going to get  all the other things related to audios and push them to the audios array
      },
    },
  ]);

  mostLikedAudios.map(async (audio) => {
    await AutoGeneratedPlaylist.updateOne(
      { title: audio._id },
      { $set: { items: audio.audios } },
      { upsert: true } // If it is not present then upsert creates it , otherwise it updates the playlist.
    );
  });

  //   res.json({ mostLikedAudios });
};

// This will run on every 24 hours
cron.schedule("0 0 * * * *", async () => {
  await generatedPlaylist();
});
